title = "yuseinishiyama.com"
baseURL = "https://yuseinishiyama.com"
enableEmoji = true
defaultContentLanguage = "ja"
hasCJKLanguage = true
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-48020408-1"

[author]
  name = "Yusei Nishiyama"

[params]
  description = "yuseinishiyama.com"
  copyright = "Copyright © 2020 Yusei Nishiyama"
  highlight = true
  amazonJpAffiliate = "usay0b-22"

[permalinks]
  posts = "posts/:year/:month/:day/:filename/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[social]
  twitter = "yuseinishiyama"
