baseurl = "https://yuseinishiyama.com"
title = "yuseinishiyama.com"
theme = "etch"
languageCode = "ja"
enableEmoji = true
defaultContentLanguage = "ja"
hasCJKLanguage = true
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-48020408-1"

[params]
description = "yuseinishiyama.com"
copyright = "Copyright © 2020 Yusei Nishiyama"
dark = "off"
highlight = true

[permalinks]
posts = "posts/:year/:month/:day/:filename/"

[languages]
[languages.ja]
weight = 1

[menu]
[[menu.main]]
name = "過去の投稿"
title = "過去の投稿"
url = "/posts"
weight = 10

[markup.goldmark.renderer]
# Allow HTML in Markdown
unsafe = true

[social]
twitter = "yuseinishiyama"