[ja]
  weight = 1

[[ja.menu.main]]
  name = "過去の投稿"
  title = "過去の投稿"
  url = "/posts"
  weight = 10

[[ja.menu.main]]
  name = "フィード"
  title = "フィード"
  url = "/index.xml"
  weight = 20

[[ja.menu.main]]
  name = "English"
  title = "English"
  url = "/en"
  weight = 30

[en]
  weight = 2

[languages.en]
  weight = 2

[[en.menu.main]]
  name = "日本語"
  title = "日本語"
  url = "/"
  weight = 30
