[ja]
  weight = 1

[[ja.menu.main]]
  name = "記事一覧"
  title = "記事一覧"
  url = "/posts"
  weight = 10

[[ja.menu.main]]
  name = "en"
  title = "en"
  url = "/en"
  weight = 20

[en]
  weight = 2

[languages.en]
  weight = 2

[[en.menu.main]]
  name = "日本語"
  title = "日本語"
  url = "/"
  weight = 30
