baseurl = "http://yuseinishiyama.com"
title = "yuseinishiyama.com"
theme = "hugo-theme-pixyll"
languageCode = "en-us"
enableEmoji = true
preserveTaxonomyNames = true
defaultContentLanguage = "ja"
hasCJKLanguage = true
metaDataFormat = "toml"
googleAnalytics = "UA-123-45"

[permalinks]
post = "posts/:year/:month/:day/:filename/"

[languages]

[languages.ja]
weight = 1

[languages.en]
weight = 2

[indexes]
category = "categories"
tag = "tags"

[params]
google_analytics_id = "UA-48020408-1"
twitter_username = "yuseinishiyama"
#disqus_shortname = ""
paginate = 5