baseurl = "https://yuseinishiyama.com"
title = "yuseinishiyama.com"
theme = "etch"
languageCode = "en-us"
enableEmoji = true
defaultContentLanguage = "ja"
hasCJKLanguage = true
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
post = "posts/:year/:month/:day/:filename/"

[languages]

[languages.ja]
weight = 1

[languages.en]
weight = 2
