baseurl = "http://yuseinishiyama.com.s3-website.eu-central-1.amazonaws.com"
title = "yuseinishiyama.com"
theme = "hugo-theme-pixyll"
languageCode = "en-us"
enableEmoji = true
preserveTaxonomyNames = true
defaultContentLanguage = "ja"

[languages]

[languages.ja]
weight = 1

[languages.en]
weight = 2

[indexes]
category = "categories"
tag = "tags"

[params]
#google_analytics_id = ""
twitter_username = "yuseinishiyama"
#disqus_shortname = ""
paginate = 5