baseurl = "http://yuseinishiyama.com.s3-website.eu-central-1.amazonaws.com/"
title = "yuseinishiyama.com"
copyright = "&copy; 2018"
theme = "zen"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
disqusShortname = ""
googleAnalytics = ""
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

[params]
  contact = "allegllet.scherzand@gmail.com"
  logo = false
  favicon = ""
[languages]

[languages.en]
weight = 1

[languages.en.params]
LanguageName = "English"

[languages.ja]
weight = 2

[languages.ja.params]
LanguageName = "Japanese"
