version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run:
          name: install AWS CLI
          command: |
            sudo apt-get install -y python3-pip
            pip3 install awscli
      - run: HUGO_ENV=production hugo -v
      - run:
          name: test generated HTML files
          command: |
            # Validate HTML but allow failure
            htmlproofer public --allow-hash-href --check-html --empty-alt-ignore --disable-external || true
      - deploy:
          name: deploy to AWS
          command: |
            aws s3 sync public/ s3://yuseinishiyama.com/ --delete
            aws cloudfront create-invalidation --distribution-id E2ZSKIG64S32BE --paths '/*'