version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run:
          name: install AWS CLI
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      - run: HUGO_ENV=production hugo -v
      - run:
          name: test generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - deploy:
          name: deploy to AWS
          command: |
            aws s3 sync $HUGO_BUILD_DIR s3://yuseinishiyama.com/ --delete
            aws cloudfront create-invalidation --distribution-id E2ZSKIG64S32BE --paths '/*'