name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker://klakegg/hugo
        with:
          args: --minify --verbose
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Publish
        run: aws s3 sync public/ s3://yuseinishiyama.com/ --delete
      - name: Invalidate Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.BLOG_AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
