name: test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: docker://klakegg/hugo
        with:
          args: --minify --verbose
      - name: Validate
        run: echo "Validate is currently disabled"
#       uses: docker://klakegg/html-proofer
#       with:
#         args: public --allow-hash-href --check-html --empty-alt-ignore --disable-external
